apiVersion: 1

datasources:
  # Prometheus - metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  # Elasticsearch - logs and search
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "*"
    jsonData:
      timeField: "@timestamp"
      esVersion: "8.12.0"
      logMessageField: message
      logLevelField: level
    editable: false
